name: Update Posts

on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby environment with ruby-build
      uses: clupprich/ruby-build-action@v1.3.0
    - name: bundle install
      run: bundler install
    - name: Import new posts
      run: bundler exec jekyll import rss --source https://dev.to/feed/dodevops
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: "chore: Adding blog posts"
        branch: ${{ github.head_ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
